### ISSUE TITLE
Automatically start on boot

### ISSUE THREAD

**Issue by dinki** [svrooij/teams-monitor#7]
First off, thanks for sharing this.  I had a version that I wrote using the old teams which read and parsed the logs.  New teams does not allow for this to work any longer so I was in need and luckily found your solution!

I'd like for this monitor to autostart on booting windows.  Is there an easy path for this?  Preferably it would be a service that would not show a powershell window.

**Comment by svrooij** [comment]
This is related to: https://github.com/svrooij/teams-monitor/issues/5#issuecomment-1825835262
