### ISSUE TITLE
Usage in my own application

### ISSUE THREAD

**Issue by FingerlessGlov3s** [svrooij/teams-monitor#8]
I'm wanting to create a simple background application, that checks the current status, plus the name of the call your in, so I can then set that status to Available.

From the sounds of it, none of this is possible currently with the library, but I can't seam to find any documentation about what actions are available on the API that Microsoft are exposing, to even try adding new actions to the library.

Currently I reset my status to Available depending what meetings/calls I'm in as that then allows people to know they can call me if needed and I can quickly go answer the call and then return to what I was doing. Currently it looks to reset the status back to `in a call` randomly. So I was hoping to automate it with the API. If there was a few simple API calls I could make to automate this, it would be great.

Where did you find what the current available actions are in your library?

**Comment by svrooij** [comment]
> Where did you find what the current available actions are in your library?
> @FingerlessGlov3s https://github.com/svrooij/teams-monitor/issues/8#issue-2228509036

Some other people documented a few, and I used wireshark to sniff the traffic. This api is undocumented by Microsoft.

The [streamdeck integration](https://apps.elgato.com/plugins/com.microsoft.teams) does no have a way to change the status, so I assume the local api does not have either.
